name: heroku deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: List file
      run: ls

    - name: Install heroku command
      run: sudo snap install --classic heroku

    - name: Heroku login
      env:
        HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        cat <<EOF > ~/.netrc
        machine api.heroku.com
          login $HEROKU_EMAIL
          password $HEROKU_API_KEY
        machine git.heroku.com
          login $HEROKU_EMAIL
          password $HEROKU_API_KEY
        EOF

    - name: Configure git
      env:
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      run: |
        git config --global user.email "$GIT_EMAIL"
        git config --global user.name "$GIT_USERNAME"
        git config --global -l

    - name: Deploy to heroku
      env:
        IFS: "\n"
      run: |
        BASE_DIR=`pwd`
        for dir in `\find * \( ! -path '*/.*' \) -maxdepth 0 -type d` ; do
          APPNAME=`cat $dir/README.md | grep appname | sed -e "s/appname:\ *//" -e "s/ *$//"`
          heroku git:remote --app $APPNAME --remote $dir
          git subtree push --prefix $dir $dir master
          for cmd in $(grep -E "^\\$" $dir/README.md | sed -e s/\\$\ //) ; do
            heroku run $cmd --app $APPNAME --remote $dir
          done
        done

