name: heroku deploy

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: List file
      run: ls
      
    - name: Install heroku command
      run: sudo snap install --classic heroku
      
    - name: Heroku login
      env:
        HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        cat <<EOF > ~/.netrc
        machine api.heroku.com
          login $HEROKU_EMAIL
          password $HEROKU_API_KEY
        machine git.heroku.com
          login $HEROKU_EMAIL
          password $HEROKU_API_KEY
        EOF
        
    - name: Heroku login check
      run: |
        cat ~/.netrc
        heroku auth:token
