name: heroku deploy

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: list file
      run: ls
      
    - name: Run a one-line script
      run: snap install --classic heroku
      
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
